grails-app/domain/todeolho/Localizacao.groovy
package todeolho

class Localizacao {

	static marshalling={

		shouldOutputVersion false
		shouldOutputClass false

	}

	String txtEndereco
	Double txtLatitude
	Double txtLongitude
	
	static belongsTo = [Localizacao]

	static constraints = {
		txtEndereco nullable:false, blank:false
		txtLatitude nullable:false, blank:false
		txtLongitude nullable:false, blank:false
	}
}

grails-app/controllers/todeolho/LocalizacaoController.groovy
package todeolho



import static org.springframework.http.HttpStatus.*
import grails.rest.RestfulController;
import grails.transaction.Transactional
import grails.converters.*

@Transactional(readOnly = true)
class LocalizacaoController extends RestfulController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
	
	LocalizacaoController(){
		super(Localizacao)
	}
	
	def showLocalizacaoAPI(){
		
		if(params.id && Denuncia.exists(params.id)) {
			def p = Localizacao.get(params.id)
			render p as JSON
		}
		else{
			def erro = ["Erro":"Dados não encontrado"]
			render erro as JSON
		}
	}
	
	def indexLocalizacaoAPI(){
		
		def all = Localizacao.list()
		render all as JSON
		
	}

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Localizacao.list(params), model:[localizacaoInstanceCount: Localizacao.count()]
    }

    def show(Localizacao localizacaoInstance) {
        respond localizacaoInstance
    }

    def create() {
        respond new Localizacao(params)
    }

    @Transactional
    def save(Localizacao localizacaoInstance) {
        if (localizacaoInstance == null) {
            notFound()
            return
        }

        if (localizacaoInstance.hasErrors()) {
            respond localizacaoInstance.errors, view:'create'
            return
        }

        localizacaoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'localizacao.label', default: 'Localizacao'), localizacaoInstance.id])
                redirect localizacaoInstance
            }
            '*' { respond localizacaoInstance, [status: CREATED] }
        }
    }

    def edit(Localizacao localizacaoInstance) {
        respond localizacaoInstance
    }

    @Transactional
    def update(Localizacao localizacaoInstance) {
        if (localizacaoInstance == null) {
            notFound()
            return
        }

        if (localizacaoInstance.hasErrors()) {
            respond localizacaoInstance.errors, view:'edit'
            return
        }

        localizacaoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Localizacao.label', default: 'Localizacao'), localizacaoInstance.id])
                redirect localizacaoInstance
            }
            '*'{ respond localizacaoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Localizacao localizacaoInstance) {

        if (localizacaoInstance == null) {
            notFound()
            return
        }

        localizacaoInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Localizacao.label', default: 'Localizacao'), localizacaoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'localizacao.label', default: 'Localizacao'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/localizacao/_form.gsp
<%@ page import="todeolho.Localizacao" %>



<div class="fieldcontain ${hasErrors(bean: localizacaoInstance, field: 'denuncias', 'error')} ">
	<label for="denuncias">
		<g:message code="localizacao.denuncias.label" default="Denuncias" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${localizacaoInstance?.denuncias?}" var="d">
    <li><g:link controller="denuncia" action="show" id="${d.id}">${d?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="denuncia" action="create" params="['localizacao.id': localizacaoInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'denuncia.label', default: 'Denuncia')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: localizacaoInstance, field: 'latitude', 'error')} required">
	<label for="latitude">
		<g:message code="localizacao.latitude.label" default="Latitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="latitude" value="${fieldValue(bean: localizacaoInstance, field: 'latitude')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: localizacaoInstance, field: 'longitude', 'error')} required">
	<label for="longitude">
		<g:message code="localizacao.longitude.label" default="Longitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="longitude" value="${fieldValue(bean: localizacaoInstance, field: 'longitude')}" required=""/>

</div>

grails-app/views/localizacao/create.gsp
<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta name="layout" content="main">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<g:set var="entityName" value="${message(code: 'localizacao.label', default: 'Localizacao')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-localizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-localizacao" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${localizacaoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${localizacaoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:localizacaoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/localizacao/edit.gsp
<%@ page import="todeolho.Localizacao"%>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta name="layout" content="crud">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<g:set var="entityName"
	value="${message(code: 'localizacao.label', default: 'Localizacao')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div id="tf-contact" class="text-center">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div id="edit-localizacao" class="content scaffold-edit"
						role="main">
						<h1>
							<g:message code="default.edit.label" args="[entityName]" />
						</h1>
						<g:if test="${flash.message}">
							<div class="message" role="status">
								${flash.message}
							</div>
						</g:if>
						<g:hasErrors bean="${localizacaoInstance}">
							<ul class="errors" role="alert">
								<g:eachError bean="${localizacaoInstance}" var="error">
									<li
										<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
											error="${error}" /></li>
								</g:eachError>
							</ul>
						</g:hasErrors>
						<g:form url="[resource:localizacaoInstance, action:'update']"
							method="PUT">
							<g:hiddenField name="version"
								value="${localizacaoInstance?.version}" />
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:actionSubmit class="save" action="update"
									value="${message(code: 'default.button.update.label', default: 'Update')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/localizacao/index.gsp
<%@ page import="todeolho.Localizacao" %>
<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta name="layout" content="main">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<g:set var="entityName" value="${message(code: 'localizacao.label', default: 'Localizacao')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-localizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-localizacao" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="latitude" title="${message(code: 'localizacao.latitude.label', default: 'Latitude')}" />

						<g:sortableColumn property="longitude" title="${message(code: 'localizacao.longitude.label', default: 'Longitude')}" />

					</tr>
				</thead>
				<tbody>
				<g:each in="${localizacaoInstanceList}" status="i" var="localizacaoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link action="show" id="${localizacaoInstance.id}">${fieldValue(bean: localizacaoInstance, field: "latitude")}</g:link></td>

						<td>${fieldValue(bean: localizacaoInstance, field: "longitude")}</td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${localizacaoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/localizacao/show.gsp
<%@ page import="todeolho.Localizacao" %>
<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta name="layout" content="main">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<g:set var="entityName" value="${message(code: 'localizacao.label', default: 'Localizacao')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-localizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-localizacao" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list localizacao">
			
				<g:if test="${localizacaoInstance?.denuncias}">
				<li class="fieldcontain">
					<span id="denuncias-label" class="property-label"><g:message code="localizacao.denuncias.label" default="Denuncias" /></span>
					
						<g:each in="${localizacaoInstance.denuncias}" var="d">
						<span class="property-value" aria-labelledby="denuncias-label"><g:link controller="denuncia" action="show" id="${d.id}">${d?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${localizacaoInstance?.latitude}">
				<li class="fieldcontain">
					<span id="latitude-label" class="property-label"><g:message code="localizacao.latitude.label" default="Latitude" /></span>
					
						<span class="property-value" aria-labelledby="latitude-label"><g:fieldValue bean="${localizacaoInstance}" field="latitude"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${localizacaoInstance?.longitude}">
				<li class="fieldcontain">
					<span id="longitude-label" class="property-label"><g:message code="localizacao.longitude.label" default="Longitude" /></span>
					
						<span class="property-value" aria-labelledby="longitude-label"><g:fieldValue bean="${localizacaoInstance}" field="longitude"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:localizacaoInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${localizacaoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>