grails-app/domain/todeolho/Perfil.groovy
package todeolho

class Perfil {

	static marshalling={

		shouldOutputVersion false
		shouldOutputClass false
		attribute 'nome'
		ignore 'imagem','curtidaToNaMidia','denuncias','comentarios',
				'cpf_cnpj','user','dataNascimento','email','status'
		deep 'curtidaToDeOlho'
	}

	String nome
	String email
	String cpf_cnpj
	Date dataNascimento
	byte[] imagem
	User user
	
	static hasMany = [denuncias:Denuncia,curtidaToDeOlho:ToDeOlho,curtidaToNaMidia:ToNaMidia,comentarios:Comentario]

	static constraints = {
		nome nullable:true, blank:false
		email nullable:true, blank:false
		cpf_cnpj nullable:true, blanck: false
		dataNascimento nullable:true, blank:false
		imagem nullable:true, maxSize:5000000
	}
	
	static mapping = {
		user cascade: "delete"
		denuncias cascade: "delete"
		curtidaToDeOlho cascade: "delete"
		curtidaToNaMidia cascade: "delete"
	}
}

grails-app/controllers/todeolho/PerfilController.groovy
package todeolho



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
@Secured(['ROLE_ADMIN','ROLE_CIDADAO','ROLE_MIDIA','ROLE_PREFEITURA'])
class PerfilController {

	def springSecurityService

	static allowedMethods = [save: "POST", delete: "DELETE"]

	def imagemUserLogado(){

		User usuario = springSecurityService.currentUser

		Perfil perfil = Perfil.findByUser(usuario)

		if(perfil){

			if(perfil.imagem){
				println("Entrou busca da imagem perfil no banco")
				response.outputStream << perfil.imagem
			}
			else{
				println("Entrou busca da imagem perfil no projeto")
				def webrootDir = servletContext.getRealPath("/") //app directory
				//def webrootDir = servletContext.getContextPath() //app directory
				println(webrootDir)
				File fileDest = new File(webrootDir,"images/team/blank.jpg")
				response.outputStream << fileDest.getBytes()
			}
		}
	}

	def imagem(){

		if(params.id == null){
			notFound()
		}

		Perfil perfil = Perfil.get(params.id as int)

		if(perfil){

			if(perfil.imagem){
				println("Entrou busca da imagem perfil no banco")
				response.outputStream << perfil.imagem
			}
			else{
				println("Entrou busca da imagem perfil no projeto")
				def webrootDir = servletContext.getRealPath("/") //app directory
				//def webrootDir = servletContext.getContextPath() //app directory
				println(webrootDir)
				File fileDest = new File(webrootDir,"images/team/blank.jpg")
				response.outputStream << fileDest.getBytes()
			}
		}
	}

	def index(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond Perfil.list(params), model:[perfilInstanceCount: Perfil.count()]
	}

	def show(Perfil perfilInstance) {
		respond perfilInstance
	}

	def create() {
		respond new Perfil(params)
	}

	@Transactional
	def save(Perfil perfilInstance) {

		def usuarioInstance = springSecurityService.currentUser

		if (usuarioInstance == null) {
			notFound()
			return
		}

		if (perfilInstance == null) {
			notFound()
			return
		}

		if (perfilInstance.hasErrors()) {
			respond perfilInstance.errors, view:'create'
			return
		}

		perfilInstance.setUser(usuarioInstance)

		perfilInstance.save()

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [message(code: 'perfil.label', default: 'Perfil'), perfilInstance.id])
				redirect perfilInstance
			}
			'*' { respond perfilInstance, [status: CREATED] }
		}
	}

	def edit() {

		def usuarioInstance = springSecurityService.currentUser

		Perfil perfil = Perfil.findByUser(usuarioInstance)

		respond perfil
	}

	@Transactional
	def update(Perfil perfilInstance) {

		println params
		println perfilInstance

		if (perfilInstance == null) {
			notFound()
			return
		}

		if (perfilInstance.hasErrors()) {
			respond perfilInstance.errors, view:'edit'
			return
		}

		def usuarioInstance = springSecurityService.currentUser

		perfilInstance.setUser(usuarioInstance)

		if(perfilInstance.save(flush:true)){
			println("Atualizou o perfil.")
		}

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'Perfil.label', default: 'Perfil'), perfilInstance.id])
				//redirect perfilInstance
				redirect(controller: "denuncia", action: "index")
			}
			'*'{ respond perfilInstance, [status: OK] }
		}
	}

	@Transactional
	def delete(Perfil perfilInstance) {

		if (perfilInstance == null) {
			notFound()
			return
		}

		// User usuario = User.get(perfilInstance.usuario.id)

		// perfilInstance.delete()
		// usuario.delete()

		// redirect(url:'/usuario/login/')

	}

	protected void notFound() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [message(code: 'perfil.label', default: 'Perfil'), params.id])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/perfil/_form.gsp
<%@ page import="todeolho.Perfil"%>


<div
	class="fieldcontain ${hasErrors(bean: perfilInstance, field: 'nome', 'error')} required">
	<div class="form-group">
		<label for="nome"> <g:message code="perfil.nome.label"
				default="Nome" /> <span class="required-indicator">*</span></label>
		<g:textField name="nome" required="" class="form-control"
			value="${perfilInstance?.nome}" />
	</div>
</div>

<div
	class="fieldcontain ${hasErrors(bean: perfilInstance, field: 'email', 'error')} required">
	<div class="form-group">
		<label for="email"> <g:message code="perfil.email.label"
				default="E-mail" /> <span class="required-indicator">*</span></label>
		<g:textField name="email" required="" class="form-control"
			value="${perfilInstance?.email}" />
	</div>
</div>

<div
	class="fieldcontain ${hasErrors(bean: perfilInstance, field: 'dataNascimento', 'error')} required">
	<div class="form-group">
		<label for="dataNascimento"> <g:message
				code="perfil.dataNascimento.label" default="Data de Nascimento" /></label>
		<g:datePicker name="dataNascimento" precision="day"
			value="${perfilInstance?.dataNascimento}" />
	</div>
</div>

<div
	class="fieldcontain ${hasErrors(bean: perfilInstance, field: 'cpf_cnpj', 'error')} required">
	<div class="form-group">
		<label for="cpf_cnpj"> <g:message code="perfil.cpf_cnpj.label"
				default="CPF/CNPJ" /> <span class="required-indicator">*</span>
		</label>
		<g:textField name="cpf_cnpj" required="" class="form-control"
			value="${perfilInstance?.cpf_cnpj}" />
	</div>
</div>

<div
	class="fieldcontain ${hasErrors(bean: perfilInstance, field: 'imagem', 'error')} required">
	<div class="form-group">
		<label for="imagem"><g:message code="perfil.imagem.label"
				default="Imagem" /></label> <input type="file" id="imagem" name="imagem"
			class="form-control" />
	</div>
</div>

grails-app/views/perfil/create.gsp
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta name="layout" content="templatePerfil">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<g:set var="entityName"
	value="${message(code: 'perfil.label', default: 'Perfil')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div id="tf-contact" class="text-center">
		<div class="container">

			<div class="row">
				<div class="col-md-8 col-md-offset-2">

					<div class="section-title center">
						<h2>
							Faça <strong>seu Cadastro</strong>
						</h2>
						<div class="line">
							<hr>
						</div>
						<div class="clearfix"></div>
						<small><em>Lorem Ipsum comes from sections 1.10.32
								and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of
								Good and Evil) by Cicero, written in 45 BC. This book is a
								treatise on the theory of ethics, very popular during the
								Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor
								sit amet..", comes from a line in section 1.10.32.</em></small>
					</div>

					<g:if test="${flash.message}">
						<div class="message" role="status">
							${flash.message}
						</div>
					</g:if>
					<g:hasErrors bean="${perfilInstance}">
						<ul class="errors" role="alert">
							<g:eachError bean="${perfilInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</g:hasErrors>

					<g:form url="[resource:perfilInstance, action:'save']" enctype="multipart/form-data" accept-charset="UTF-8">
						<fieldset class="form">

							<g:render template="form" />
							<button type="submit" class="btn tf-btn btn-default">Salvar</button>
						</fieldset>
					</g:form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/perfil/edit.gsp
<%@ page import="todeolho.Perfil"%>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta name="layout" content="templatePerfil">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<g:set var="entityName"
	value="${message(code: 'perfil.label', default: 'Perfil')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div id="tf-contact" class="text-center">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">

					<div class="section-title center">
						<h2>
							Atualize <strong>seu Perfil</strong>
						</h2>
						<div class="line">
							<hr>
						</div>
						<div class="clearfix"></div>
						<small><em>Preencha os dados abaixo corretamente. 
						Você tem completa responsabilidade sobre os mesmos</em></small>
					</div>

					<div id="edit-perfil" role="main">
						<g:if test="${flash.message}">
							<div class="message" role="status">
								${flash.message}
							</div>
						</g:if>
						<g:hasErrors bean="${perfilInstance}">
							<ul class="errors" role="alert">
								<g:eachError bean="${perfilInstance}" var="error">
									<li
										<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
											error="${error}" /></li>
								</g:eachError>
							</ul>
						</g:hasErrors>
						<g:form url="[resource:perfilInstance, action:'update']" enctype="multipart/form-data" accept-charset="UTF-8">
							<g:hiddenField name="version"
								value="${perfilInstance?.version}" />
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<button type="submit" class="btn tf-btn btn-default">Atualizar</button>
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/perfil/index.gsp
<%@ page import="todeolho.Perfil"%>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta name="layout" content="templatePerfil">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<g:set var="entityName"
	value="${message(code: 'perfil.label', default: 'Perfil')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div id="tf-contact" class="text-center">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="section-title center">
						<h2>
							<strong>Perfil</strong>
						</h2>
						<div class="line">
							<hr>
						</div>
						<div class="clearfix"></div>
					</div>


					<div id="list-perfil" class="content scaffold-list" role="main">
						<h1>
							<g:message code="default.list.label" args="[entityName]" />
						</h1>
						<g:if test="${flash.message}">
							<div class="message" role="status">
								${flash.message}
							</div>
						</g:if>
						<table class="table table-bordered">
							<thead>
								<tr>

									<g:sortableColumn property="nome"
										title="${message(code: 'perfil.nome.label', default: 'Nome')}" />

									<g:sortableColumn property="email"
										title="${message(code: 'perfil.email.label', default: 'Email')}" />

									<g:sortableColumn property="usuario"
										title="${message(code: 'perfil.usuario.label', default: 'Login')}" />
								</tr>
							</thead>
							<tbody>
								<g:each in="${perfilInstanceList}" status="i"
									var="perfilInstance">
									<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

										<td><g:link action="show" id="${perfilInstance.id}">
												${fieldValue(bean: perfilInstance, field: "nome")}
											</g:link></td>

										<td>
											${fieldValue(bean: perfilInstance, field: "email")}
										</td>

										<td>
											${fieldValue(bean: perfilInstance.usuario, field: "login")}
										</td>

									</tr>
								</g:each>
							</tbody>
						</table>
						<div class="pagination">
							<g:paginate total="${perfilInstanceCount ?: 0}" />
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/perfil/show.gsp
<%@ page import="todeolho.Perfil"%>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta name="layout" content="templatePerfil">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<g:set var="entityName"
	value="${message(code: 'perfil.label', default: 'Perfil')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<div id="tf-contact" class="text-center">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="section-title center">
						<h2>
							Detalhes <strong>do Perfil</strong>
						</h2>
						<div class="line">
							<hr>
						</div>
						<div class="clearfix"></div>
					</div>

					<div id="show-perfil" role="main">
						<g:if test="${flash.message}">
							<div class="message" role="status">
								${flash.message}
							</div>
						</g:if>
						
						<g:if test="${perfilInstance?.imagem}">
							<p class="fieldcontain">
								<span class="property-value" aria-labelledby="imagem-label">
									<img
									src="${createLink(controller:'perfil', action:'imagem',id:perfilInstance?.id)}"
									style="width: 60px; height: 60px;" />
								</span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.nome}">
							<p class="fieldcontain">
								<span id="nome-label" class="property-label">Nome: </span> <span
									class="property-value" aria-labelledby="nome-label"><g:fieldValue
										bean="${perfilInstance}" field="nome" /></span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.usuario}">
							<p class="fieldcontain">
								<span id="usuario-label" class="property-label">Login: </span> <span
									class="property-value" aria-labelledby="usuario-label">
									${perfilInstance?.usuario?.login}
								</span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.email}">
							<p class="fieldcontain">
								<span id="email-label" class="property-label">E-mail: </span> <span
									class="property-value" aria-labelledby="email-label"><g:fieldValue
										bean="${perfilInstance}" field="email" /></span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.dataNascimento}">
							<p class="fieldcontain">
								<span id="dataNascimento-label" class="property-label">Data
									de Nascimento: </span> <span class="property-value"
									aria-labelledby="dataNascimento-label"><g:formatDate
										date="${perfilInstance?.dataNascimento}" /></span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.cpf_cnpj}">
							<p class="fieldcontain">
								<span id="cpf_cnpj-label" class="property-label">CPF/CNPJ:
								</span> <span class="property-value" aria-labelledby="cpf_cnpj-label">
									<g:fieldValue bean="${perfilInstance}" field="cpf_cnpj" />
								</span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.status}">
							<p class="fieldcontain">
								<span id="status-label" class="property-label">Status: </span> <span
									class="property-value" aria-labelledby="status-label"><g:formatBoolean
										boolean="${perfilInstance?.status}" /></span>
							</p>
						</g:if>

						<g:if test="${perfilInstance?.tipoPerfil}">
							<p class="fieldcontain">
								<span id="tipoPerfil-label" class="property-label">Tipo
									Perfil: </span> <span class="property-value"
									aria-labelledby="tipoPerfil-label"><g:fieldValue
										bean="${perfilInstance}" field="tipoPerfil" /></span>
							</p>
						</g:if>

						<g:form url="[resource:perfilInstance, action:'delete']"
							method="DELETE">
							<fieldset class="buttons">
								<g:link class="edit" action="edit"
									class="btn tf-btn btn-default" resource="${perfilInstance}">
									Editar
								</g:link>
								<g:actionSubmit class="btn tf-btn btn-danger" action="delete"
									value="Excluir"
									onclick="return confirm('Confirme a exclusão do registro!');" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>